### ISSUE TITLE
Mamy instrukcję jak dołączyć do testów na `stag`

### ISSUE THREAD

**Issue by jakublipinski** [ProteGO-app/specs#14]
Instrukcja powinna być tutaj: https://github.com/ProteGO-app/specs/blob/master/specs/testing.md

Myślę, że warto zbierać adresy e-mail np. przez Google Form i dodawać je cyklicznie do TestFlight / Google Play.

**Comment by rtpm** [comment]
Formularz póki co niedostępny "na zewnątrz".

**Comment by tomaszmnich** [comment]
Formularz został udostępniony publicznie.
