### ISSUE TITLE
Co z trollowaniem?

### ISSUE THREAD

**Issue by darthkurak** [ProteGO-app/specs#20]
Skoro użytkownik z aplikacji będzie mógł ustawić swój status - w jaki sposób aplikacja ma zapobiec trollowaniu i wysyłaniu nieprawdziwych sytuacji?
Skoro i tak aplikacja ma być podpięta pod GIS (GIS dostanie info o sieci kontaktów zarażonego), to może GIS powinien wprowadzać zarażonych?

**Comment by rtpm** [comment]
Gdzie jest informacja, że użytkownik sam może ustawić swój status ?
Nie wydaje mi się, aby to było możliwe.

**Comment by darthkurak** [comment]
https://www.gov.pl/web/cyfryzacja/zycie-po-kwarantannie--przetestuj-protego - tutaj:
`Skąd w systemie pojawia się informacja o potencjalnym ryzyku? Od zarażonego. To ta osoba, w pełni anonimowo, informuje o zmianie swojego stanu zdrowia zaznaczając to w aplikacji.`
Ale fakt, doczytałem teraz tutaj na repo, że to GIS kontaktuje się zarażonym i prosi o przesłanie danych.
Czyli jeżeli dobrze rozumiem, flaga po stronie systemu (że pacjent jest zarażony) jest ustawiana przez GIS?

**Comment by rtpm** [comment]
Użytkownik używa apki.. okazuje się, że jest zarażony (odpowiedni test potwierdzający.. w tym momencie GIS z nim się kontaktuje i prosi go o przesłanie danych). Sam tego GIS nie robi.
Użytkownik świadomie wysyła do GIS dane telefonów, które "napotkał" przez ostatnie 2 tygodnie. 
Są to oczywiście identyfikatory nic nie znaczące dla użytkownika, nawet ich nie widzi. Po prostu jednym przyciskiem wysyła dane. Oczywiście od momentu pozyskania przez GIS informacji wiedzy, że użytkownik jest zarażony, zmienia się status tego użytkownika na czerwony.

**Comment by darthkurak** [comment]
Super, dzięki za info. W takim razie przydałoby się zedytować info tutaj:
https://www.gov.pl/web/cyfryzacja/zycie-po-kwarantannie--przetestuj-protego
Bo z tego tekstu wynika, że to użytkownik wprowadza swój status :)

**Comment by darthkurak** [comment]
Btw, czy użytkownik może odmówić przesłania danych telefonów które spotkał przez 2 tygodnie?

**Comment by rtpm** [comment]
Technicznie tak. Po prostu nie wysyła - nie naciska odpowiedniego przycisku. Na dzień dzisiejszy nie ma opcji, że system sam "ciągnie" dane od użytkownika. Nie wiem jak to będzie wyglądać prawnie.
Być może później, ale pewnie na początkowym etapie twórcy bazują bardziej na woli użytkownika, z oczywistych powodów...

**Comment by darthkurak** [comment]
No i wszystko wiadomo! Dzięki za odpowiedzi.

**Comment by milist** [comment]
Zasysanie tych identyfikatorów przez GIS nie będzie dobrze odebrane, gdyż teoretycznie będzie GIS mógł zassać wszystkie dane i śledzić (a takich posądzeń chyba chcemy uniknąć, żeby ludzie nie bali się apki instalować)
