### ISSUE TITLE
send_encounters performance

### ISSUE THREAD

**Issue by arsoba** [ProteGO-app/specs#22]
How many requests to the send_encounters endpoint to you expect?
Why don't you use HTTP for this endpoint? Do you think about other protocols? MQTT for example.

**Comment by AlexF0rtune** [comment]
From what I've understood, encounters ( that is, who met who ) shall not be transmitted to remote server unless one will be found to be infected with the coronavirus - this is , as I understand, a privacy concern. 

Source:
https://www.gov.pl/web/cyfryzacja/zycie-po-kwarantannie--przetestuj-protego

**Comment by arsoba** [comment]
I thought the main point is to link all historical connections.
Example. Today the user is not infected but in 4 days we'll know that the user is infected.

**Comment by jakublipinski** [comment]
The data is voluntarily shared by end-users only if there are diagnosed with SARS-CoV-2. Thus we are not expecting tons of data on the server. Please reopen if you need further clarification.
