### ISSUE TITLE
Nadmiar danych w protokole

### ISSUE THREAD

**Issue by D0han** [ProteGO-app/specs#27]
Wysyłanie os_version oraz device_type przy każdym zapytaniu brzmi jak zbędna operacja. Zastanowiłbym się też nad potrzebą trzymania tego w bazie. Jaki jest tego cel?

**Comment by rtpm** [comment]
Dobrze widzę, że to jest aktualizowane przy każdym odpytaniu /get_status ?

**Comment by jakublipinski** [comment]
Po zmianie telefonu, można zarejestrować się przy pomocy tego samego numeru. Wtedy trzeba zaktualizować `device_type`. `os_version` na urządzeniu może się zmienić. Ponieważ aktualizujemy pole `last_status_requested` zaktualizowanie pozostałych jest znikomym kosztem.

**Comment by D0han** [comment]
> Zastanowiłbym się też nad potrzebą trzymania tego w bazie. Jaki jest tego cel?
Nie widzę powiązania pomiędzy zbieraniem tych danych a celem projektu

**Comment by jakublipinski** [comment]
Nie będziemy mieli żadnych Google Analytics, Crashalitycs itp
Chcemy wiedzieć na jakich telefonach/systemach działa aplikacja aby móc podejmować decyzję o szukaniu bug'ów, wspieraniu poszczególnych wersji, priorytetyzacji.

**Comment by cloudyfuel** [comment]
@jakublipinski Czy samo wysłanie `device_type` i `os_version` rzeczywiście rozwiązuje ten problem? Samo wysłanie tej informacji nie znaczy, że aplikacja działa poprawnie. Myślę, że dane te nie powinny być wysyłane. W celu testowania aplikacji można posłużyć się opiniami w sklepach Google Play i App Store, dobrowolną pomocą użytkowników, którzy z pewnością zechcą pomóc jak również szerokimi testami na różnych urządzeniach, o które Ministerstwo powinno zadbać. Dobrowolna pomoc może być przeprowadzana przez github, przycisk bug report w aplikacji, statystyki opt-in matomo.

Jeśli telemetria ma być wykorzystywana w aplikacji, powinna być opt-in i mieć jasno określony cel (w tej chwili nie widzę za bardzo korzyści, a widzę szkody). Przede wszystkim obywatel powinien być w pełni świadom konsekwencji swoich dobrowolnych działań w co uwzględnione powinno być zjawisko lenistwa i niedoinformowania użytkowników - długie, ukryte polityki prywatności, dark patterns, opt-out nie pomagają.
