### ISSUE TITLE
Bluetooth - nadawanie i jednoczesne skanowanie w tle, IOS

### ISSUE THREAD

**Issue by wino45** [ProteGO-app/specs#28]
Cześć

Czy ktoś sprawdził czy można jednocześnie skanować (słuchać) i nadawać pakiety Bluetooth/Bluetooth Low Energy przez aplikacje IOS pracująca w tle ?
Może to nie być w ogóle możliwe ze względu na ograniczenia IOS API. 
Jeżeli jest możliwe, to jak bardzo zużywa to baterię ? Zarówno skanowanie jak i nadawanie zużywa energię.

**Comment by mkwiecinski** [comment]
Nie jest to możliwe wprost. Na Androidzie są podobne ograniczenia, zwłaszcza u Chińskich producentów którzy ubijają aplikacje w tle.

Można próbować to obejść, ale tylko częściowo. Podczas monitorowania UUID jeśli zostanie odczytany UUID związany z „ProteGo” można odpalić w tle aplikację aby odnotować ten fakt i, być może, także wysłać „odpowiedz”. Problem nr 1 jest taki, ze Apple ogranicza odpalanie w tle do 180 sekund. Można wysłać użytkownikowi local notification gdy odczytamy ze pozostało już kilka sekund (jest remaining time w którymś parametrze). Wtedy użytkownik będzie ponaglony do uruchomienia aplikacji, tylko w celu zresetowania licznika. 

Problem drugi jest w tym, ze to zadziała tylko gdy iOS jest odpowiadającym. Gdy spotkają się 2 iOSy lub iOS z ograniczonym Androidem - spotkanie nie będzie zarejestrowane ([źródło](http://www.davidgyoungtech.com/2019/04/30/the-rise-of-the-nasty-forks) )

Jestem tez ciekawy jak chcecie w cała przestrzeń dostępna w major i minor iBeacona upakować jednorazowe tokeny, o których jest rozmowa w [Issue 34](https://github.com/ProteGO-app/specs/issues/34)

**Comment by kgluszczyk** [comment]
Na Androidzie zawsze można skorzystać z foreground service + screen
overlay. Nigdy nie będzie 100% pewności, ale w końcu we wszystkim tylko
minimalizujemy prawdopodobieństwo ;)

**Comment by jakublipinski** [comment]
Tutaj opisaliśmy nasze podejście: https://github.com/ProteGO-app/specs/blob/master/specs/bluetooth.md

**Comment by jakublipinski** [comment]
Dajcie znać czy coś jeszcze jest niejasne, albo zamknijcie proszę

**Comment by jakublipinski** [comment]
Z braku pytań zamykam
