### ISSUE TITLE
Informacja o projekcie

### ISSUE THREAD

**Issue by rtpm** [ProteGO-app/specs#30]
Rozmawiałem z kilkoma osobami / znajomymi ze świata dev'u i zachodzi pytanie o to, kto stoi za projektem. Przydałby się dokument, który jasno wyjaśnia, kto stoi za projektem i jakie jest jego
powiązanie z organami Państwa, tj. czy stoi za tym dodatkowa firma, jak wygląda finansowanie.

Widać tutaj, że dużo commit'ów jest z Warszawskiej firmy. Nie wiem, czy wrzucane commit'y są prezentem dla nas obywateli, czy idą za tym pieniądze. Ja osobiście nie mam nic przeciw, że ktoś być może zarobi, ktoś inny nie..  jednakże każdy, kto być może będzie chciał dorzucić swoją cegiełkę, na pewno jest zainteresowany informacją o projekcie, jego założeniach i (ewentualnym) finansowaniu.

Szczególnie ma to znaczenie w dobie ostatnich projektów, pojawiających się bardziej lub mniej prawdziwych informacji o ich finansowaniu itd. Brak informacji może być blockerem dla chcących angażować się w projekt.

**Comment by jakublipinski** [comment]
Cześć, super, że rozważacie zaangażowanie się. 

Do dzisiejszego dnia kiedy otworzyliśmy kod, głównymi kontrybutorami w projekcie były osoby z firmy [Polidea](https://www.polidea.com). Pisaliśmy dziś o tym w naszym [komunikacie](https://twitter.com/polidea/status/1246020669067984896). Teraz kiedy projekt jest otwarty, mamy nadzieję na zaangażowanie innych osób.

Praca nad ProteGO do działalność _pro bono_ Polidei i jej zespołu.

**Comment by kgluszczyk** [comment]
@jakublipinski planujecie upublicznić wasz kanał komunikacji (slack?) i boarda projektowego(trello?) dla zainteresowanych?

**Comment by AlexF0rtune** [comment]
O to to, potrzebujemy jakoś z Wami rozmawiać!

**Comment by potiuk** [comment]
W szczególności musi być jasne kto jest właścicielem licencji. Nawet jeśli to jest licencja GPL/AGPL (co jest bardzo dobre) to musi być jasne kto jest właścicielem.

**Comment by jakublipinski** [comment]
Próbuję ogarnąć te tematy prawne z Ministerstwem Cyfryzacji i prawnikami. Czy ktoś ma jakiś przykład projektu open-source **z Polski**, który jakoś ten temat ogarnął?

**Comment by potiuk** [comment]
https://en.wikipedia.org/wiki/Moose_File_System

**Comment by potiuk** [comment]
Bardzo dobry przykład. Mogę Cię @jakublipinski skontaktować z twórcami.

**Comment by jakublipinski** [comment]
Czy to możemy już zamknąć?

**Comment by jakublipinski** [comment]
Licencja jest. Sposób współpracy też. Zamykam.
