### ISSUE TITLE
Branding i design system

### ISSUE THREAD

**Issue by wojtekszkutnik** [ProteGO-app/specs#44]
Im bardziej projekt rośnie, tym istotniejsza jest spójna warstwa graficzna i UX (szczególnie w aplikacji przeznaczonej dla ogółu populacji). Czy istnieje w tym momencie jakakolwiek specyfikacja jednego lub drugiego?

**Comment by Tarvald** [comment]
Myśle że wersją 1.0.0 nie będzie miała za dużo improvmentów na poziomie UX.
Dużo ważniejsza jest funkcjonalność oraz wdrożenie aplikacji w życie.

**Comment by wojtekszkutnik** [comment]
A jest jakiś design w ogóle? Bo na githubie niczego nie widać, stąd pytanie

**Comment by kierepka** [comment]
Możemy udostępnić nasz UI w razie potrzeby i akceptacji oczywiście.

**Comment by optimusbits** [comment]
Jest jakiś clickflow zrobiony do wymagań w issusach dla aplikacji mobilnych? (Adobe XD, inVission) ?

**Comment by jakublipinski** [comment]
Dzięki, że pytacie, udostępniliśmy właśnie wszystko [tutaj](https://github.com/ProteGO-app/specs/blob/master/CONTRIBUTING.md#Zajmuj%C4%99-si%C4%99-uxui-jak-mog%C4%99-pom%C3%B3c). Dajcie znać jeśli macie jakieś pomysły/usprawnienia w konkretnych `issues`.
Mogę zamknąć?

**Comment by wojtekszkutnik** [comment]
Wygląda jak dobry start 👍🏻Na dłuższą metę fajnie byłoby to wystawić np na sketch cloudzie, wtedy ludzie mogliby dawać feedback bez konieczności ściągania plików

**Comment by jakublipinski** [comment]
Śmiało!  Możesz to zrobić i zorganizować :)

**Comment by wojtekszkutnik** [comment]
Wrzuciłem obecną wersję tutaj, natomiast ważne żeby osoby, uaktualniające sketcha uploadowały nowe wersje do clouda. Contributorów proszę o kontakt na wojtek@tango.agency to dodam :)
