### ISSUE TITLE
Sposób podejmowania decyzji w projekcie - czym jest community w tym projekcie?

### ISSUE THREAD

**Issue by potiuk** [ProteGO-app/specs#46]
W tej chwili nie wiadomo w jaki sposób podejmowane są decyzje projektowe. Kto decyduje o tym jakie rzeczy wchodzą a jakie nie wchodzą, jaki jest protokół. W Projektach open-source zawsze istnieje "governance model" . Na przykład w fundacji Apache i jej projektach jest on zdefiniowany i jasno udokumentowany:

https://www.apache.org/foundation/governance/

Jeśli nie ma zdefiniowanego modelu, i nie wiadomo, kto jest właścicielem kodu ani projektu, nie ma mowy o tym, żeby był to projekt rozwijany przez community a taka jest narracja Minsterstrwa Infrastruktury. 

Czy można się dowiedzieć jak ten model wygląda ?

**Comment by jakublipinski** [comment]
Kwestie własności kodu opisałem [tutaj](https://github.com/ProteGO-app/specs/blob/master/CONTRIBUTING.md#oświadczenie-o-udzieleniu-licencji)

Kwestie decyzji opisałem [tutaj](https://github.com/ProteGO-app/specs/blob/master/CONTRIBUTING.md#kto-podejmuje-decyzje-w-tym-projekcie):

ProteGO ma jedynie sens jeśli zostanie stworzone we współpracy z administracją. Potrzebujemy połączenia z zaufanym źródłem informacji dotyczącym tego czy ktoś został zakażony SARS-CoV-2. Taki rejestr jest prowadzony przez stronę rządową. Ministerstwo Cyfryzacji (MC) zdecydowało się wydać i promować tę aplikację. Oznacza to jednak również to, że ostatecznie to MC decyduje o tym czy aplikacja i jej kolejne wersje będą wydane. Potrzebujemy więc współpracy i dialogu, który połączy potrzeby i obawy każdej ze stron. **Aktualnie** łącznikiem między MC i projektem jestem ja. Chętnie oddam to komuś chętnemu (praca 24x7 bez wynagrodzenia)

Jeśli można to zrobić lepiej - chętnie posłucham waszych pomysłów. To chyba pierwszy tak poważny projekt open-source dla administracji. Marzę aby jednym z jego efektów było pokazanie, że da się robić open-source'owe projekty dla sektora publicznego.

**Comment by potiuk** [comment]
Super. Jak dla mnie można spokojnie zamknąć.
