### ISSUE TITLE
Błędny właściel oprogramowania w  licencji

### ISSUE THREAD

**Issue by potiuk** [ProteGO-app/specs#50]
Z licencji wynika, że właścicielem oprogramowania jest Free Software Foundation. To jest niezgodne z rzeczywistością. Nie wiadomo kto jest właścicielem oprogramowania.

https://github.com/ProteGO-app/specs/blob/master/LICENSE

**Comment by jakublipinski** [comment]
Właścicielem (autorem) licencji z której korzystamy jest Free Software Foundation.

Właścicielem oprogramowania jest jego autor/autorka. Autor kontrybuując do repozytorium z określoną licencją [udziela jej na swoją pracę](https://help.github.com/en/github/site-policy/github-terms-of-service#6-contributions-under-repository-license).

**Comment by potiuk** [comment]
Fakatycznie. Żle zatytułowałem issue. Poprawiłem na "Błędny właściciel oprogramowania w licencji. Dzięki za zwrócenie uwagi. Meritum sprawy pozostaje. 

Właściciel i autot to dwa zupełnie inne pojęcia.

W Licencji należy napisać kto jest właścicielem oprogramowania. Właściciel != autor. Autor jest autorem i ma prawo autorskie, którego nie może komu innemu przekazać, natomiast prawo własności może i najczęściej tak się dzieje na przykład na mocy https://www.apache.org/licenses/icla.pdf w przypadku Apache Software Foundation, gdzie "ownership" jest przekazywane do Fundacji. Dotyczy to zarówno pojęcia :copyright", jak i "patent right", Każdy kto kontrybuje do projektu open-source w ASF przekazuje te prawa (nie "autorstwo/authorship" ale "ownership") organizacji która jest właścicielem oprogramowania.

W wypadku ProteGo kompletnie nie wiadomo kto jest "właścicielem" - wiadomo kto jest "autorem".

**Comment by jakublipinski** [comment]
Właścicielem jest autor, dopóki nie przekaże swoich praw własności czego nie wymagamy. Wystarcza udzielenie licencji.

**Comment by potiuk** [comment]
> Właścicielem jest autor, dopóki nie przekaże swoich praw własności czego nie wymagamy. Wystarcza udzielenie licencji.

Komu?

**Comment by jakublipinski** [comment]
> Komu?

Każdemu kto tej licencji przestrzega.

**Comment by potiuk** [comment]
Licencja jest zawsze dawana przez kogoś w tej chwili licencję w tym projekcie (czyli jego własność) ma Free Software Foundation (zgodnie z https://www.apache.org/licenses/icla.pdf), Chyba zaraz do nich napiszę że właśnie dostali ciekawy projekt,

**Comment by potiuk** [comment]
warto by to sprawdzić z prawnikami

**Comment by jakublipinski** [comment]
Tak, licencja jest dawana przez autorów oprogramowania.

Tak, właścicielem naszej licencji jest Free Software Foundation.

**Comment by potiuk** [comment]
OK. Dzięki za wyjaśnienie. Czyli nikomu nikt nie przekazuje własności w tym przupadku (inaczej niż w przypadku projektów Apache Software Foundation, gdzie przekazuje się własność oprogramowania do ASF). Jasne. Dzięki za wytłumaczenie. Zamykam to issue i zostaje teraz tylko kwestia podejmowania decyzji w projekcie #46 do wyjaśnienia.
