### ISSUE TITLE
Nie rozumiem tych zagadnień - trochę za dużo szans na FP

### ISSUE THREAD

**Issue by kierepka** [ProteGO-app/specs#52]
My tworząc CoronaHack rozważaliśmy takie sytuacje jako słabe:
1) Jadą dwa autobusy obok siebie - wszyscy komunikują się bluetooth, liczba false positive ogromna (nie wspomnę o pociągu itp)
2) Czy nie lepiej zrobić jak u nas - włączamy tryb jesteśmy w pobliżu i świadomie zgłaszamy i świadomie potwierdzamy? Coś jak spotkanie? 

Idea  CoronaHack jest zbieżna z założeniami  ProteGO (szczegóły w załączonym i wysłanym PDF), gdzie dodatkowo uwypuklono szczególnie ważny aspekt pracowników służby zdrowia ponieważ wiemy jakie są konsekwencje dla szpitali przy nieprzerwanym w porę łańcuchu zakażeń.
Jako lekarz dr Kownacki zwraca uwagę na definicję "kontaktu" zgodną z WHO, ponieważ aplikacja puszczona w trybie całkowite "auto na Bluetooth" wywołać może więcej szkód (panika/niepewność) niż korzyści. Stąd adekwatne założenia opisane w CoronaHack.

Zgłoszenie robiliśmy na Hack the Crisis.
http://coronalog.pl/?page_id=2

**Comment by kierepka** [comment]
https://www.spidersweb.pl/2020/04/protego.html tu też opisana podobna apka w singapurze -  TraceTogether. Tu nazwane "cyfrową piątką".

**Comment by Tarvald** [comment]
Ja np. bardzo często zapominam włączyć endomondo kiedy idę biegać. Mimo że bardzo zależy mi na śledzeniu każdego treningu.
Myśle że tak samo będzie z protego.

Takie dwa autobusy ile mogą jechać obok siebie? 1 min ? 2 min? 10 min w jakiś ekstremalnych warunkach.

Do tego bluethooth szczególnie, ta wersja low energy raczej powinna zostać skutecznie zatrzymana przez dwie ściany autobusu, a nawet jeżeli będzie kontakt, to będzie on odrazu dużo dużo słabszy niż przy otwartej przestrzeni.

Mam racje?

**Comment by kierepka** [comment]
No nie całkiem

  | BLUETOOTH v2.1 | BLUETOOTH 5 (LE)
Range | Up to 100 m | Up to 400 m
Max range (free field) | Around 100 m (class 2 outdoors) | Around 1,000m (outdoors)
Frequency | 2.402 – 2.481 GHz | 2.402 - 2.481 GHz
Max data rate | 1- 3 Mbit/s | 2 Mbit/s

I to bez żadnych wzmacniaczy (no i w warunkach idealnych, ale jednak jeden kilometr...)

**Comment by jakublipinski** [comment]
Duplicate #62
