### ISSUE TITLE
Przymusowa aplikacja "kwarantanna domowa" wysyłająca zdjęcia na serwer

### ISSUE THREAD

**Issue by SeraMoon** [ProteGO-app/specs#53]
Niestety po tym jak dobrowolna aplikacja "kwarantanna domowa" mimo zapewnień danych publicznie, że nie stanie się obowiązkowa - stała się obowiązkowa - nie zamierzam pomagać w rozwoju aplikacji, która potencjalnie później może zostać użyta do kolejnych tak "szczytnych celów" przez dodanie kolejnych funkcji. Skompromitowaliście się państwo z Ministerstwa Zdrowia (Ministry of Health in Poland). 

Za takie traktowanie obywateli + dążenie do władzy po trupach przez PiS (jedna z partii politycznych), niszczenie gospodarki rodzimej i jednego z kandydatów na prezydenta- nie ma wybaczenie i nie będzie. Do widzenia, wolę wspierać inne krainy. 

Odebraliście nam nawet prawo do bezpośredniego głosowania, wbrew zapisom Konstytucji. **WStYD**!

Nie macie też za grosz poszanowania dla prywatności obywateli, zmuszając ich wbrew RODO do wyrażenia PRZYMUSOWEJ zgody na przesyłanie ich danych biometrycznych na serwery firmy trzeciej lub rządowe. Nie informujecie, że ich dane będą PRZYMUSOWO wysłane do Google (Android) oraz Apple (iOS) i tą zgodę wymuszacie. Ludzie mając Anroida i iOS, mogli mieć do tej pory zaklejoną kamerę i nie dzielić się z Google i iOS zdjęciami.

**Comment by jakublipinski** [comment]
Nie mamy nic wspólnego z Kwarantanną Domową. Proszę swoje uwagi zgłosić pod odpowiedni adres.

**Comment by SeraMoon** [comment]
Macie dużo wspólnego z tym, bowiem aplikacja jest przygotowywana dla polskiego rządu:
https://www.gov.pl/web/cyfryzacja/zycie-po-kwarantannie--przetestuj-protego (GOV.PL)

podobnie jak kwarantanna domowa:
https://www.gov.pl/web/cyfryzacja/aplikacja-kwarantanna-domowa--od-dzis-obowiazkowa (też GOV.PL).

Protego stanie tanie się kiedyś kolejnym narzędziem opresji polskich obywateli. Zrobicie im bazę do tego, aby włączyli tam funkcje kwarantanny domowej, śledzenia obywateli i inne funkcje opresji społeczeństwa. 

Do tego cytat:
"Oto nasze założenie: aplikację ProteGO, bo taką nazwę nosi projekt, przygotowuje społeczność polskich programistów, projektantów, grafików i testerów. Wyda ją Ministerstwo Cyfryzacji. Zanim jednak to zrobimy zapraszamy innych programistów i testerów do jej sprawdzenia. Już dziś udostępniamy jej kod źródłowy."

Aplikację "Kwarantanna Domowa" też wydało Ministerstwo Cyfryzacji. Proszę wszystkich, którym zależy na naszej prywatności do bojkotu tej aplikacji.
