### ISSUE TITLE
Apel o usunięcie numeru telefonu przy rejestracji lub odłączenie numeru od identyfikatorów BT

### ISSUE THREAD

**Issue by potiuk** [ProteGO-app/specs#56]
Numer telefonu jest niepotrzebny przy rejestracji. Dużo o tym jest napisane w #34 #55 #54 więc nie będę się więcej rozpisywał.

Jeśli obecnie jest potrzeba szybkiego wdrożenia aplikacji żeby zacząć gromadzić dane na telefonach, apeluję do osób tworzących o usunięcie konieczności rejestracji przynajmniej z pierwszej wersji aplikacji i debatę publiczną na temat wdrożenia rozwiązania nie naruszającego prywatności. 

---- 
Aktualizacja 6.04.2020

Wydaje się że akceptowalnym rozwiązaniem będzie podawanie numeru telefonu przy rejestracji, które nie będzie w żaden sposób związane z identyfikatorami BT generowanymi tylko na urządzeniiu i wysyłanymi na serwer. Jest to opisane tu:

https://github.com/ProteGO-app/specs/issues/34#issuecomment-609676552

To rozwiązanie (pod warukiem nadzoru organizacji NGO nad procesem publikacji aplikacji i przeglądania kodu źródłowego) spełnia wszystkie warunki postawione zarówno przez osoby które dbają o prywatność, jak i Ministerstwo Cyfryzacji:

1) Nie można zidentyfikować i zdeanonimizować identyfikatorów BT po stronie serwera
2) Numer telefonu jest obowiązkowy (ale przechowywany tylko lokalnie)
3) Aplikacja po sprawdzeniu że jej identyfikatory są zagrożone wysyła informację o swoim numerze telefonu do serwera tak aby GIS wiedział, że powinien się z taką osobą skontaktować. Ta informacja nie zawiera identyfikatorów bluetooth i uniemożliwia ich połączenie z numerem telefonu.

**Comment by potiuk** [comment]
Mam zarmiar rozpocząć kampanię społeczną dotyczącą tego apelu i zaangażować do tego poważne organizacje NGO. Mam sporo kontaktów w tym obszarze. Bardzo proszę osoby, które chciałyby dołączyć do tej inicjatywy o śledzenie tego issue - będę publikował informacje jak tylko będę miał szczegóły.

**Comment by Tarvald** [comment]
Na początku kiedy od dwóch dni czytam twoje posty, trochę się denerwowałem że o wszystko się czepiasz, w imię prywatności i demokracji. Ja osobiście wolałbym dąć numer i mieć pewność że jestem bezpieczny.
Ale teraz zrozumiałem że jak nie ty, to może ktoś inny... kto może nie być skory do współpracy.
Więc dziękuję za zaangażowanie :)

Przetrzymywanie numerów telefonów pozwoliłoby na szybkie działanie sanepidowi.
Co jeżeli ktoś się zbuntuje, nie poda historii, oleje sprawę?

Np. jakiś pijaczyna, albo menel albo inny degenerat społeczny, któremu nie na rękę będzie kwarantanna, badanie oraz kontakt z urzędnikami?

**Comment by potiuk** [comment]
Pijaczyna i menel nie zainstaluje aplikacji

**Comment by AdvenamTacet** [comment]
> Np. jakiś pijaczyna, albo menel albo inny degenerat społeczny, któremu nie na rękę będzie kwarantanna, badanie oraz kontakt z urzędnikami?

Jeśli ktoś w ogóle nie chce (lub nie może) współpracować, to nie będzie współpracował. Co zostało już wspomniane.

Najważniejsze aby jednak jak najwięcej osób chciało współpracować. A do tego potrzeba rozwiązań zapewniających bezpieczeństwo i prywatność (jako podstawowe prawo człowieka).

Istnieją też uzasadnione przypadki, gdy ktoś może nie móc wyrazić zgody, aby jakiś serwer mógł prześledzić historię jego ruchów, a nadal chcieć być poinformowanym o potencjalnym zagrożeniu.
Najbardziej wymownym przykładem są osoby odpowiedzialne za bezpieczeństwo państwa, ale "zwykły obywatel" też może być w tej grupie.

**Comment by D0han** [comment]
Zgadzam się z tym, że numer telefonu nie powinien być zbierany od samego początku. Inaczej adopcja rozwiązania w społeczeństwie zwyczajnie nie nastąpi.

**Comment by kfigaj** [comment]
https://forsal.pl/artykuly/1466954,epidemiczny-wielki-brat-mc-ma-otrzymywac-dane-lokalizacyjne-zdrowych-osob.html - Za chwilę może się okazać, że nie będzie potrzebny numer telefonu. Dane dostanie bezpośrednio ministerstwo od operatorów tel komu bez potrzeby zgody sądu.

**Comment by potiuk** [comment]
Uwaga. Rząd dostanie takie możliwości:
a) informacja o lokalizacji osób chorych przez ostatnie 2 tygodnie z GSM
b) Informacja z ProteGO na temat widzianych "pseudo-aonimowych" identyfikatorów przez te ostatnie 2 tygodnie (sami wyślemy) 
c) Informacja z ProteGo na temat mapowania między "pseudo-anonimowych" identyfikatorów i numeru telefonu (przechowywane na serwerze ProteGO)

a) + b) + c) - i możemy przy nawet kilku procentach ludzi chorych odtworzyć praktycznie cały graf bliskich spotkań wszystkich ludzi w Polsce wraz z czasem i lokalizacją.

Super.

**Comment by D0han** [comment]
W świetle tych dodatkowych uprawnień i danych od operatorów ProteGO jest całkowicie zbędne.

**Comment by potiuk** [comment]
Najpierw musiałyby przejśc w tej formie .. To na razie plotlka medialna. I o ile wyciąganie informacji o ludziach zdrowych może nie przejść, o tyle o chorych może (na zasadzie wprowadzania kozy - "OK dobra, nie będziemy wszystkiego wyciągać tylko dane o ludziach chorych") . I wtedy patrz wyżej - ProteGO jak znalazł żeby uzupełnić brakujące dane.

**Comment by JAN4GER** [comment]
POPIERAM

**Comment by JAN4GER** [comment]
JEST SUPER
https://www.youtube.com/watch?v=kfH1hxvAN30

> https://forsal.pl/artykuly/1466954,epidemiczny-wielki-brat-mc-ma-otrzymywac-dane-lokalizacyjne-zdrowych-osob.html - Za chwilę może się okazać, że nie będzie potrzebny numer telefonu. Dane dostanie bezpośrednio ministerstwo od operatorów tel komu bez potrzeby zgody sądu.

**Comment by przem123** [comment]
Bez numeru telefonu byloby duzo prosciej. Ja domyslam sie, ze zielony status w okresie przejsciowym daje mozliwosci wejscia do miejsc na razie zamknietych, typu kina, dyskoteki itd. I tam bedzie sie odbywala weryfikacja. Jesli ktos nie ma aplikacji to bedzie traktowany jak osoba ze statusem pomanczowym tj. wyjscia tylko do pracy, sklepu, lekarza jak dzisiaj. W zwiazku z tym likwidacja obowiazku numeru telefonu powinna byc rozwazona.

**Comment by mikolak** [comment]
> Bez numeru telefonu byloby duzo prosciej. Ja domyslam sie, ze zielony status w okresie przejsciowym daje mozliwosci wejscia do miejsc na razie zamknietych, typu kina, dyskoteki itd. I tam bedzie sie odbywala weryfikacja. Jesli ktos nie ma aplikacji to bedzie traktowany jak osoba ze statusem pomanczowym tj. wyjscia tylko do pracy, sklepu, lekarza jak dzisiaj. W zwiazku z tym likwidacja obowiazku numeru telefonu powinna byc rozwazona.

Jeśli z określonego statusu będą wynikać korzyści indywidualne, to stanie się to polem do nadużyć. Wystarczy zainstalować aplikację na starym telefonie i ją potrzymać w domu przez dwa tygodnie.

**Comment by potiuk** [comment]
> Jeśli z określonego statusu będą wynikać korzyści indywidualne, to stanie się to polem do nadużyć. Wystarczy zainstalować aplikację na starym telefonie i ją potrzymać w domu przez dwa tygodnie.

Po pierwsze rozwiązanie z numerem telefonu ma ten sam problem. Równie dobrze można mieć dwie aplikacje zarejestrowane na dwa numery i trzymać drugi telefon w domu. 


Po drugie bardzo łatwo się przed tym zabezpieczyć. Wystarczy co jakiś czas sprawdzać, czy aplikacja styka się z nowymi numerami bluetooth, czy bluetooth jest włączony i czy zmienia się lokalizacja urządzenia.

**Comment by potiuk** [comment]
Uwaga. Pojawił się nowy pomysł na rozwiązanie obu problemów na raz. Rozwiązanie wymusza podawanie numeru telefonu (i przechowywanie go lokalnie i jednocześnie utrzymywanie anonimowych identyfikatorów BT). Szczegóły tu: https://github.com/ProteGO-app/specs/issues/34#issuecomment-609676552. Dostosowałem odpowiednio opis i tytuł issue.

**Comment by mikolak** [comment]
> > Jeśli z określonego statusu będą wynikać korzyści indywidualne, to stanie się to polem do nadużyć. Wystarczy zainstalować aplikację na starym telefonie i ją potrzymać w domu przez dwa tygodnie.
> 
> Po pierwsze rozwiązanie z numerem telefonu ma ten sam problem. Równie dobrze można mieć dwie aplikacje zarejestrowane na dwa numery i trzymać drugi telefon w domu.

Mój komentarz w żaden sposób nie dotyczył numeru telefonu. 

> Po drugie bardzo łatwo się przed tym zabezpieczyć. Wystarczy co jakiś czas sprawdzać, czy aplikacja styka się z nowymi numerami bluetooth, czy bluetooth jest włączony i czy zmienia się lokalizacja urządzenia.

Od dwóch tygodni nie wyszedłem z domu. Zgodnie z tą logiką jestem oszustem, który trzyma telefon w mikrofalówce albo po prostu nie istnieję. 😉

**Comment by potiuk** [comment]
> Mój komentarz w żaden sposób nie dotyczył numeru telefonu.

Twój komentarz był komentarzem do mojego wpisu "Bez numeru telefonu byloby duzo prosciej." więc założyłem, że to jest komentarz dotyczący tego :).

> 
> > Po drugie bardzo łatwo się przed tym zabezpieczyć. Wystarczy co jakiś czas sprawdzać, czy aplikacja styka się z nowymi numerami bluetooth, czy bluetooth jest włączony i czy zmienia się lokalizacja urządzenia.
> 
> Od dwóch tygodni nie wyszedłem z domu. Zgodnie z tą logiką jestem oszustem, który trzyma telefon w mikrofalówce albo po prostu nie istnieję.

W zasadzie ta część dyskusji może być zamknięta. Zaproponowany pomysł https://github.com/ProteGO-app/specs/issues/34#issuecomment-609676552 dalej ma numer telefonu (i aplikacja go zna) ale jednocześnie nie łączy identyfikatorów BT i numeru telefonu - co daje dokładnie takie same możliwości jak oryginalne rozwiązanie tylko z zachowaniem prywatności. To jest nawet lepsze rozwiązanie niż pozbycie się numeru, więc możemy o tej ewentualności (i zabezpieczeniach z nich wynikających) nie rozmawiać.

**Comment by jakublipinski** [comment]
W świetle https://github.com/ProteGO-app/specs/issues/34#issuecomment-609993832 sugeruję zamknąć ten wątek.

**Comment by potiuk** [comment]
Tak jak naisane w dokumentacji w  b486959, 694cc66, 336a7bb -  mamy teraz możliwość anonimowej rejestracji. Na tą chwilę to adresuje większość problemów powyżej - więc spokojnie można to zamknąć.
