### ISSUE TITLE
Czy trzeba być z Warszawy aby brać udział w projekcie? Problemy z oświadczeniem

### ISSUE THREAD

**Issue by jasisz** [ProteGO-app/specs#57]
Sam tytuł issuesa jest oczywiście żartem, ale proces udzielania licencji jest bardzo niedoskonały.
1. Nie ma w tej chwili możliwości potwierdzenia że podpisujący dokument jest jednocześnie właścicielem "identyfikatora na platformie GitHub".
2. Nie każdy jest z Warszawy, więc nie każdy może wypełnić ten formularz. Rozumiem że mogę sobie zmienić akurat ten fragment, ale nie mogę zmienić innych fragmentów? Na przykład licencję na której udostępniam kod?
3. Wydaje mi się, że jest to po prostu proces, którego większość osób potencjalnie zainteresowanych kontrybuowaniem nie będzie chciała pzrechodzić. Podobne oświadczenia w przeszłosci wielokrotnie odrzuciły mnie od przeróżnych projektów.

**Comment by potiuk** [comment]
Tak. To oświadczenie (dodane przed chwilą) daleko wykracza poza cokolwiek co jest określone w licencji.

**Comment by potiuk** [comment]
Oświadczenie jest tu: https://github.com/ProteGO-app/specs/blob/master/files/oswiadczenie_licencja_GPL_AGPL.pdf

**Comment by jakublipinski** [comment]
Dzięki za czujność. Usunąłem Warszawę.

@jasisz może jest tak jak mówisz. 10 dni zajęło mi przekonanie administracji, jak podchodzić do projektu open-source. Domyślnie kupują prawa, płacą, nie masz szans zobaczyć kodu. 

W ProteGO próbujemy inaczej. To pewnie pierwszy tego typu projekt w Polsce. Przykro mi jeśli nie spełnia Twoich oczekiwań.

**Comment by D0han** [comment]
W dokumencie jest mowa o aplikacji na urządzenia mobilne. Czy obejmuje to wszystkie repozytoria projektu? W tym część serwerową?

**Comment by jakublipinski** [comment]
Tak. Wszystko pod adresem: https://github.com/ProteGO-app/*

**Comment by jasisz** [comment]
Co z osobami z zagranicy, które chciałyby się włączyć? W jaki sposób mają użyć podpisu? Czy będzie oświadczenie po angielsku?

**Comment by jakublipinski** [comment]
Poczekajmy na pierwszą osobę z zagranicy

**Comment by D0han** [comment]
Oprogramowanie serwerowe nie brzmi jak aplikacja na urządzenia mobilne.

**Comment by kierepka** [comment]
Co z wykorzystaniem innych wcześniejszych projektów z HackTheCrisis? My robiliśmy https://github.com/kierepka/CoronaLog w ramach tego projektu - i przemyślenia oraz projekt przygotował Dr Kownacki, grafikę też mamy gotową od mojego brata. Złożymy odpowiednie dokumenty, ale obecny projekt trzeba przemyśleć jeszcze raz (my to robiliśmy w trybie ekspresowym i walcząc z paroma założeniami). Czyli projekt jest bardzo zbliżony i powstał ponad 3 tygodnie temu...
http://coronalog.pl/?page_id=2

**Comment by potiuk** [comment]
Ciekawy jestem założeń jeśli chodzi o prywatność waszego rozwiązania @kierepka ? Możecie napisać coś więcej na ten temat ? Również w kontekście #55 #54 i #56 - na ile wasze rozwiązanie wpisuje się w to, co tam było ? Może właśnie to wasza aplikacja powinna być wdrażana, jeśli nie uda się zwalczyć problemów z prywatnością w projekcie ProteGO ?

**Comment by kierepka** [comment]
No właśnie o to chodzi:
1) Po tych paru tygodniach widzę, że zarówno nasze podejście, podejście TraceTogether i CoronaLog (tak ta sama nazwa co nasza) z Estonii bazująca na google, dadzą tyko to do czego mogą posłużyć - ostrzeganie tylko tych co się zaznaczyło, że się z nimi spotkało. Robienie tego za nas przez algorytm - bo to będzie **bardzo** niedokładne.
2) Tylko Google, operatorzy GSM i podobne służby mogą jasno powiedzieć z kim się mogliśmy spotkać z _większym_ prawdopodobieństwem
Tylko te dwa źródła razem dadzą w _miarę_ dokładne informacje.

Obecny model działania jest dość podatny na dużą ilość błędów i problemów technicznych.
My planowaliśmy to tak podczas HackTheCrisis:
https://cdn.filestackcontent.com/1r34bMhJRmb0bqgKORIV
Teraz trochę bym to pouzupełniał i wiedząc to co wiem po 3 tygodniach podszedłbym do tematu na pewno ciut inaczej.

**Comment by jakublipinski** [comment]
> Oprogramowanie serwerowe nie brzmi jak aplikacja na urządzenia mobilne.

Dzięki za czujność. Doprecyzowałem ponownie: https://github.com/ProteGO-app/specs/commit/383865026b8000231744c0102ec3c0bcd0884086

Mam nadzieję, że jest OK teraz.

**Comment by kierepka** [comment]
@jakublipinski  zgłoszenie i wejście do projektu zespołu z CoronaHack (CoronaLog) wysłane do ministerstwa. Prośba o informację zwrotną jak dalej brać udział w pracach i projekcie (czy robić fork, czy może jednak tutaj) połączyć to co robiliśmy?

**Comment by jakublipinski** [comment]
@kierepka super, witajcie na pokładzie. Może opisz w osobnym issue jakie elementy CoronaLog można byłoby ew. wykorzystać w ProteGO?

Teraz jesteśmy maksymalnie zajęci wypuszczeniem `1.0`. Jeśli możecie pomóc w testach lub robić audyty kodu - byłoby super. Potem będziemy planować dalsze prace.

**Comment by jakublipinski** [comment]
Czy można to zamknąć?

**Comment by jasisz** [comment]
@jakublipinski Zamykam.
