### ISSUE TITLE
Brak ruchomego elementu na ekranie statusu

### ISSUE THREAD

**Issue by przem123** [ProteGO-app/specs#68]
Domyslam sie, ze aplikacja bedzie wykorzystywana do potwierdzenia mozliwosci wejscia dla osob z zielonym statusem do miejsc dotychczas zamknietych, na przyklad kina, restauracji itd. W zwiazku z tym warto by dodac jakis element ruchomy obok statusu np. aktualna godzine z sekundami (lub date aktualizacji statusu rowna aktualnemu dniu), bo inaczej mozna screenshotem manipulowac wlasnym statusem.

**Comment by JAN4GER** [comment]
Proponuje wykorzystać status również przed zgodą na kupowaniem alkoholu (włacznie z piwem). Taki sam pomysł.

**Comment by przem123** [comment]
Closing as it is design related.
