### ISSUE TITLE
Zasady wspolpracy - branching strategy

### ISSUE THREAD

**Issue by badziomiki** [ProteGO-app/specs#76]
Witam wszystkich, wraz z moim zespolem jestesmy zainteresowani wsparciem ProteGo. Na ta chwile celujemy w aplikacje iOS/Android. Czy jest gdzies opisana zasada wspolpracy z uwypukleniem tego na jakiej zasadzie dziala 'branchowanie' projektu?

Pozdrawiam
Michal

**Comment by pawelByszewski** [comment]
Cześć,
obecnie repozytorium jest prowadzone banalnie prosto. Mamy mastera i dla każdej nowej funkcjonalności/usprawnienia/poprawki błędu robimy brancha. Jeśli jest gotowy to mergowany jest bezpośrednio do mastera. Gdy zbliżymy się do wejścia na produkcję  lub będziemy prowadzili rozbudowane testy z użytkownikami wtedy mamy plan przejść na [git flow](https://datasift.github.io/gitflow/IntroducingGitFlow.html). Dzięki temu będziemy mieli możliwość zamrażania wersji do wydania, wprowadzania hotfixów przy utrzymaniu intensywne developmentu nowych funkcjonalności.

**Comment by pawelByszewski** [comment]
Jednocześnie zanim możemy wciągnąć jakiegokolwiek PR muszą być spełnione wymagania formalne:
W tym celu należy wypełnić [oświadczenie o przekazaniu licencji](https://github.com/ProteGO-app/specs/blob/master/CONTRIBUTING.md#O%C5%9Bwiadczenie-o-udzieleniu-licencji). Po potwierdzeniu od Ministerstwa Cyfryzacji otrzymania dokumentu, możemy zmergować PR.

**Comment by jakublipinski** [comment]
Dzięki @pawelByszewski Wrzuciłem Twój opis tutaj: https://github.com/ProteGO-app/specs/blob/master/CONTRIBUTING.md#jaki-mamy-branching-strategy i zamykam.
