### ISSUE TITLE
Punktacja w aplikacji

### ISSUE THREAD

**Issue by stefan-paluch** [ProteGO-app/specs#80]
Wyczytałem że w Korei (tej z wirusem) zachęcają ludzi do pozostawania w domu podczas kwarantanny dając im pieniądze za każdy dzień kiedy są w domu – domyślam się że jeśli wyjdą z domu to tracą te pieniądze.

Ta aplikacja mogłaby też mieć taki system ‘punktów’ – np.: aplikacja działała cały dzień – dostaniesz 10zł, aplikacja zarejestrowała jeden nowy nieznany identyfikator bluetooth – straciłeś 1zł itp. mogą być dużo mniejsze kwoty, albo jakieś kupony czy punkty – myślę że to by zachęciło część ludzi do używania aplikacji – w ten sposób jej działanie byłoby mniej ‘abstrakcyjne’.

**Comment by jasisz** [comment]
@stefan-paluch to każdy by wyłączał Bluetooth 😄 a chyba nie taki jest cel...

**Comment by stefan-paluch** [comment]
To fakt - ale teraz też mogę wyłączyć BT zanim pójdę do sklepu i włączyć w domu - nie ma za to żadnej kary - ani nagrody; tzn. - jest nagroda. ale - za wyłączenie BT: w ten sposób zminimalizuję szansę że mój BT trafi do kogoś kto na drugi dzień będzie chory i wciągnie mnie na testy albo kwarantanne.
Mam na myśli że powinienem chcieć mieć włączony BT - tzn. żeby to opłacało mi się bardziej niż postępowanie zgodne z ekonomią.

**Comment by kgluszczyk** [comment]
Element gamefikacji może mieć pozytywny wpływ na odbiór aplikacji. Kary na
nieprzestrzeganie obecnych regulacji są rzeczywiście wysokie, ale zamiast
naliczania pieniędzy, wprowadził bym bagde za kolejne dni z włączonym
bluetoothem. Nagradzanie za unikanie ludzi może prowadzić do negatywnych
emocji w miejscach, gdzie nie da się ich zbytnio uniknąć ;)
